if(EXISTS "/Users/csv610/Projects/Mesh/ShapeOp/tests/unit_tests[1]_tests.cmake")
  include("/Users/csv610/Projects/Mesh/ShapeOp/tests/unit_tests[1]_tests.cmake")
else()
  add_test(unit_tests_NOT_BUILT unit_tests_NOT_BUILT)
endif()
