# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _shapeopPython
else:
    import _shapeopPython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class intArray(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, nelements):
        _shapeopPython.intArray_swiginit(self, _shapeopPython.new_intArray(nelements))
    __swig_destroy__ = _shapeopPython.delete_intArray

    def __getitem__(self, index):
        return _shapeopPython.intArray___getitem__(self, index)

    def __setitem__(self, index, value):
        return _shapeopPython.intArray___setitem__(self, index, value)

    def cast(self):
        return _shapeopPython.intArray_cast(self)

    @staticmethod
    def frompointer(t):
        return _shapeopPython.intArray_frompointer(t)

# Register intArray in _shapeopPython:
_shapeopPython.intArray_swigregister(intArray)
class doubleArray(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, nelements):
        _shapeopPython.doubleArray_swiginit(self, _shapeopPython.new_doubleArray(nelements))
    __swig_destroy__ = _shapeopPython.delete_doubleArray

    def __getitem__(self, index):
        return _shapeopPython.doubleArray___getitem__(self, index)

    def __setitem__(self, index, value):
        return _shapeopPython.doubleArray___setitem__(self, index, value)

    def cast(self):
        return _shapeopPython.doubleArray_cast(self)

    @staticmethod
    def frompointer(t):
        return _shapeopPython.doubleArray_frompointer(t)

# Register doubleArray in _shapeopPython:
_shapeopPython.doubleArray_swigregister(doubleArray)
SO_SUCCESS = _shapeopPython.SO_SUCCESS
SO_INVALID_CONSTRAINT_TYPE = _shapeopPython.SO_INVALID_CONSTRAINT_TYPE
SO_INVALID_ARGUMENT_LENGTH = _shapeopPython.SO_INVALID_ARGUMENT_LENGTH
SO_UNMATCHING_CONSTRAINT_ID = _shapeopPython.SO_UNMATCHING_CONSTRAINT_ID

def shapeop_create():
    return _shapeopPython.shapeop_create()

def shapeop_delete(op):
    return _shapeopPython.shapeop_delete(op)

def shapeop_init(op):
    return _shapeopPython.shapeop_init(op)

def shapeop_initDynamic(op, masses, damping, timestep):
    return _shapeopPython.shapeop_initDynamic(op, masses, damping, timestep)

def shapeop_solve(op, iteration):
    return _shapeopPython.shapeop_solve(op, iteration)

def shapeop_setPoints(op, points, nb_points):
    return _shapeopPython.shapeop_setPoints(op, points, nb_points)

def shapeop_getPoints(op, points, nb_points):
    return _shapeopPython.shapeop_getPoints(op, points, nb_points)

def shapeop_setTimeStep(op, timestep):
    return _shapeopPython.shapeop_setTimeStep(op, timestep)

def shapeop_setDamping(op, damping):
    return _shapeopPython.shapeop_setDamping(op, damping)

def shapeop_addConstraint(op, constraintType, ids, nb_ids, weight):
    return _shapeopPython.shapeop_addConstraint(op, constraintType, ids, nb_ids, weight)

def shapeop_editConstraint(op, constraintType, constraint_id, scalars, nb_scl):
    return _shapeopPython.shapeop_editConstraint(op, constraintType, constraint_id, scalars, nb_scl)

def shapeop_addGravityForce(op, force):
    return _shapeopPython.shapeop_addGravityForce(op, force)

def shapeop_addVertexForce(op, force, id):
    return _shapeopPython.shapeop_addVertexForce(op, force, id)

def shapeop_editVertexForce(op, force_id, force, id):
    return _shapeopPython.shapeop_editVertexForce(op, force_id, force, id)

